spring.application.name=KhataWeb



spring.datasource.url=jdbc:mysql://localhost:3306/khataweb
spring.datasource.username=Ishka
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true   

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=6000
spring.redis.connect-timeout=5000

springdoc.api-docs.title=My Spring Boot API
springdoc.api-docs.version=OPENAPI_3_1
springdoc.api-docs.description=This is the Swagger documentation for my project
springdoc.swagger-ui.path=/docs

#http://localhost:8080/swagger-ui.html

server.port=8080
server.address=0.0.0.0