spring.application.name=KhataWeb



spring.datasource.url=jdbc:mysql://192.168.29.143:3306/khataweb
spring.datasource.username=Ishka
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true   